elastic_url = ''
elastic_password = ''
elastic_api_key = ''

openai_api_key = ''
openai_api_type = 'azure'
openai_api_base = ''
openai_api_version = '2023-07-01-preview'
openai_api_model = 'gpt3.5-turbo'

aws_access_key=''
aws_secret_key=''
aws_region=''
aws_model_id='anthropic.claude-v2'